apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-api
  labels:
    app: brain-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-api
  template:
    metadata:
      labels:
        app: brain-api
    spec:
      containers:
        - name: api
          image: brain-tumor/api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: brain-api-config
            - secretRef:
                name: brain-api-secrets
          volumeMounts:
            - name: artifacts
              mountPath: /app/ml/artifacts
            - name: feedback
              mountPath: /app/data/weak_feedback
      volumes:
        - name: artifacts
          persistentVolumeClaim:
            claimName: brain-artifacts
        - name: feedback
          persistentVolumeClaim:
            claimName: brain-feedback
