apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.yaml
  - pvc-artifacts.yaml
  - pvc-feedback.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - retrainer-cronjob.yaml
