apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brain-tumor-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://example.com/your-repo.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
